# Generated by Django 3.1.3 on 2020-11-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.TextField(default='img-1.png'),
        ),
    ]
