# Generated by Django 3.1.3 on 2020-11-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201124_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='+91 0000-0000-00', max_length=25),
        ),
    ]
