# Generated by Django 3.1.3 on 2020-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifieds',
            name='cities',
            field=models.ManyToManyField(to='core.City'),
        ),
    ]
