# Generated by Django 3.1.3 on 2020-12-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classifieds_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifieds',
            name='category',
        ),
        migrations.AddField(
            model_name='classifieds',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
            preserve_default=False,
        ),
    ]
